image: dcr.danawa.io/alpine-k8s

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  when: manual
  script:
    - npm install -g react-scripts && npm install

deploy:
  stage: deploy
  when: manual
  script:
    - env

