image: dcr.danawa.io/alpine-k8s

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  when: manual
  script:
    - npm install -g react-scripts && npm install && npm run build
    - docker build -H 119.205.194.100:2375 -t "${REGISTRY}/${CI_PROJECT_PATH}:${CI_PIPELINE_ID}" .
    - docker push "${REGISTRY}/${CI_PROJECT_PATH}:${CI_PIPELINE_ID}"

deploy:
  stage: deploy
  when: manual
  script:
    - env

