image: dcr.danawa.io/alpine-k8s

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Kubectl Install"
    - npm run build
    - docker build -t "${REGISTRY}/${CI_PROJECT_PATH}:${CI_PIPELINE_ID}" .
    - docker push "${REGISTRY}/${CI_PROJECT_PATH}:${CI_PIPELINE_ID}"

deploy:
  stage: deploy
  script:
    - env

