image: dcr.danawa.io/alpine-k8s

variables:
  GIT_STRATEGY: clone

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  when: manual
  script:
    - npm install && npm run build
    - export IMAGE="${REGISTRY}/${CI_PROJECT_TITLE}:${CI_PIPELINE_ID}"
    - echo "${IMAGE}"
    - docker build -t "${IMAGE}" .
    - docker push "${IMAGE}"

deploy:
  stage: deploy
  when: manual
  script:
    - export IMAGE="${REGISTRY}/${CI_PROJECT_TITLE}:${CI_PIPELINE_ID}"
    - echo "${IMAGE}"
    - kubectl patch deployment fastcatx-console -n fastcatx --patch '{"spec": {"template": {"spec": {"containers": [{"name": "fastcatx-console", "image": ${IMAGE} }]}}}}'

