image: dcr.danawa.io/alpine-k8s

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/


before_script:
#  - export app_version=$(grep version package.json | awk '{print $2}'|sed 's/[\",]//g')
#  - export IMAGE="${REGISTRY}/${CI_PROJECT_TITLE}:${app_version}-${CI_BUILD_ID}"
  - export IMAGE="${REGISTRY}/${CI_PROJECT_TITLE}:latest"
  - echo "${IMAGE}"

module install:
  stage: install
  when: manual
  script:
    - npm install -g npm
    - rm -rf yarn.lock
    - rm -rf package-lock.json
    - npm cache clean -f
    - rm -rf node_modules
    - npm install

build:
  stage: build
  script:
    - npm install -g yarn
    - yarn build --reset-cache
    - docker build -t "${IMAGE}" .
    - docker push "${IMAGE}"

deploy:
  stage: deploy
  cache: {}
  script:
    - kubectl patch deployment fastcatx-console -n fastcatx -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}},\"spec\":{\"containers\":[{\"name\":\"fastcatx-console\",\"image\":\"${IMAGE}\"}]}}}}"
    - sleep 5
    - kubectl get pod -n fastcatx -o wide


