image: dcr.danawa.io/alpine-k8s

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  when: manual
  script:
    - npm install -g react-scripts && npm install && npm run build
    - export IMAGE = "${REGISTRY}/${CI_PROJECT_PATH}:${CI_PIPELINE_ID}"
    - echo "${IMAGE}"
    - docker build -t "${IMAGE}" .
    - docker push "${REGISTRY}/${IMAGE}"

deploy:
  stage: deploy
  when: manual
  script:
    - env

